# Generated by Django 4.2.23 on 2025-07-08 07:57

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_policyrenewal_unique_policy_validity_to_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='enrolment_period_end_date',
            field=core.fields.DateField(blank=True, db_column='EnrolmentPeriodEndDate', help_text='End date of the enrollment period for this policy', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='enrolment_period_start_date',
            field=core.fields.DateField(blank=True, db_column='EnrolmentPeriodStartDate', help_text='Start date of the enrollment period for this policy', null=True),
        ),
    ]
