# Generated by Django 4.2.23 on 2025-07-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_membership_types'),
        ('policy', '0012_policy_enrolment_period_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='membership_type',
            field=models.ForeignKey(blank=True, db_column='MembershipTypeID', help_text='Selected membership type for this policy.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policies', to='product.membershiptype'),
        ),
    ]
